spring.application.name=tienda-web-express

server.port=8080

# PostgreSQL (Commented out)
# spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_web_express
# spring.datasource.username=baxava
# spring.datasource.password=medifind_baxava
# spring.datasource.driver-class-name=org.postgresql.Driver

# H2 Database
spring.datasource.url=jdbc:h2:mem:tienda_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console