spring.application.name=tienda-web-express

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_web_express
spring.datasource.username=baxava
spring.datasource.password=medifind_baxava
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false